### ISSUE TITLE
Improve napari installation instructions?

### ISSUE THREAD

**Issue by tischi** [royerlab/ultrack#84]
I tried installing ultrack as specified in the README.txt but then trying to run napari throws the below error:

```
>>> napari.run()
Traceback (most recent call last):
  File "/g/cba/miniconda3/envs/ultrack_jupyter/lib/python3.10/site-packages/napari/_qt/__init__.py", line 8, in <module>
    from qtpy import API_NAME, QtCore
  File "/g/cba/miniconda3/envs/ultrack_jupyter/lib/python3.10/site-packages/qtpy/__init__.py", line 287, in <module>
    raise QtBindingsNotFoundError from None
qtpy.QtBindingsNotFoundError: No Qt bindings could be found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/g/cba/miniconda3/envs/ultrack_jupyter/lib/python3.10/site-packages/napari/_event_loop.py", line 12, in run
    raise exc
  File "/g/cba/miniconda3/envs/ultrack_jupyter/lib/python3.10/site-packages/napari/_event_loop.py", line 2, in <module>
    from napari._qt.qt_event_loop import gui_qt, run
  File "/g/cba/miniconda3/envs/ultrack_jupyter/lib/python3.10/site-packages/napari/_qt/__init__.py", line 18, in <module>
    raise ImportError(
ImportError: No Qt bindings could be found.

napari requires either PyQt5 (default) or PySide2 to be installed in the environment.

With pip, you can install either with:
  $ pip install -U 'napari[all]'  # default choice
  $ pip install -U 'napari[pyqt5]'
  $ pip install -U 'napari[pyside2]'

With conda, you need to do:
  $ conda install -c conda-forge pyqt
  $ conda install -c conda-forge pyside2

Our heuristics suggest you are using 'pip' to manage your packages.
```

**Comment by JoOkuma** [comment]
Hi @tischi, napari doesn't come with a Qt backend.

`pip install napari[all]` should do the trick.

 Or the other suggestion from the error message:

```
With pip, you can install either with:
  $ pip install -U 'napari[all]'  # default choice
  $ pip install -U 'napari[pyqt5]'
  $ pip install -U 'napari[pyside2]'

With conda, you need to do:
  $ conda install -c conda-forge pyqt
  $ conda install -c conda-forge pyside2
```

**Comment by tischi** [comment]
I also tried installing napari before with conda, but then when I then tried to install ultrack via pip on top many core libraries like numpy and pandas are changed, which does not feel good....

**Comment by JoOkuma** [comment]
😓 this seems like a napari issue. I don't think `numpy` or `pandas` are the issue. It looks lower in the software stack.

Are you running in a node? Does it have OpenGL and other visualization drivers?
